name: Protik Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu al
        uses: actions/checkout@v4

      - name: Node.js kur
        uses: actions/setup-node@v4
        with:
          node-version: 22
          

      - name: Paketleri yükle
        run: npm install

      - name: Projeyi derle
        run: npm run build
